source :gemcutter

gem "yard"
gem "extlib", "~> 0.9.0"
gem "erubis", "~> 2.6.2"
gem "rake"
gem "rack"
gem "mime-types", ">= 1.16"

gem "memcache-client", :require => 'memcache'

gem "rspec", "~> 1.2.0"
gem "webrat", "~> 0.3.0"


